#!/bin/sh

set -ex

if [ -z $GITHUB_ACTIONS ]; then
    scripts/check
fi

export COVERAGE_PROCESS_START=$(pwd)/pyproject.toml

uv run coverage run --debug config -m pytest "$@"

if [ -z $GITHUB_ACTIONS ]; then
    scripts/coverage
fi
